# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "bot"
      - "dependabot"
      - "dependencies"
      - "skip:test:long_running"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 1-5"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "bot"
      - "dependabot"
      - "dependencies"
      - "skip:test:long_running"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 1-5"
