name: "> Build Native Only"

on:
  workflow_call:
    # No secrets needed

env:
  # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
  PYTHONIOENCODING: "utf8"

jobs:

  build_native:

    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
        experimental: [false]
        include:
          - runner: ubuntu-24.04-arm
            experimental: true
          - runner: macos-latest
            experimental: true
          - runner: macos-15-intel
            experimental: true
          - runner: windows-latest
            experimental: true
          - runner: windows-11-arm
            experimental: true

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5
        with:
          version-file: "pyproject.toml"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install upx for native Windows version
        if: ${{ matrix.runner == 'windows-latest' || matrix.runner == 'windows-11-arm' }}
        shell: bash
        run: |
          choco install upx --no-progress

      - name: Build native distribution into dist_native/
        shell: bash
        run: make dist_native

      - name: Upload dist_native artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ always() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        with:
          name: dist_native-${{ matrix.runner }}
          path: dist_native/aignostics.7z
          retention-days: 1
