name: "Report build to Ketryx and check for approval"

on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
    secrets:
      KETRYX_PROJECT:
        required: false
      KETRYX_API_KEY:
        required: false

env:
  # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
  PYTHONIOENCODING: "utf8"

jobs:
  ketryx_report_and_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Download test results for ubuntu-latest generated in _test.yml
        if: (!contains(github.event.head_commit.message, 'skip:ketryx'))
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: test-results-ubuntu-latest

      - name: Download audit results generated in _audit.yml
        if: (!contains(github.event.head_commit.message, 'skip:ketryx'))
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: audit-results

      - name: Report build to Ketryx and check for approval
        if: (!contains(github.event.head_commit.message, 'skip:ketryx'))
        uses: Ketryx/ketryx-github-action@40b13ef68c772e96e58ec01a81f5b216d7710186 # v1.4.0
        continue-on-error: true # TODO(Helmut): Remove post having Ketryx configured to inspect the main branch
        with:
          project: ${{ secrets.KETRYX_PROJECT }}
          api-key: ${{ secrets.KETRYX_API_KEY }}
          commit-sha: ${{ inputs.commit-sha }}
          build-name: "ci-cd"
          check-dependencies-status: true
          test-junit-path: reports/junit_*.xml
          cyclonedx-json-path: |
            reports/sbom.json
          artifact-path: |
            reports/sbom.spdx
            reports/licenses.csv
            reports/licenses.json
            reports/licenses_grouped.json
            reports/vulnerabilities.json
            reports/mypy_junit.xml
            reports/coverage.xml
            reports/coverage.md
            # aignostics.log
