name: "> Ketryx Report and Check"

on:
  workflow_call:
    inputs:
      commit_message:
        description: 'Commit message to check for skip markers'
        required: false
        type: string

      commit-sha:
        required: true
        type: string
    secrets:
      KETRYX_PROJECT:
        required: false
      KETRYX_API_KEY:
        required: false

env:
  # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
  PYTHONIOENCODING: "utf8"

jobs:
  ketryx_report_and_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Download test results for ubuntu-latest generated in _test.yml
        if: |
          !contains(inputs.commit_message, 'skip:ketryx') &&
          !contains(github.event.pull_request.labels.*.name, 'skip:ketryx')
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: test-results-ubuntu-latest
          path: test-results

      - name: Download audit results generated in _audit.yml
        if: |
          !contains(inputs.commit_message, 'skip:ketryx') &&
          !contains(github.event.pull_request.labels.*.name, 'skip:ketryx')
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: audit-results
          path: audit-results

      - name: Report build to Ketryx and check for approval
        if: |
          !contains(inputs.commit_message, 'skip:ketryx') &&
          !contains(github.event.pull_request.labels.*.name, 'skip:ketryx')
        uses: Ketryx/ketryx-github-action@40b13ef68c772e96e58ec01a81f5b216d7710186 # v1.4.0
        with:
          project: ${{ secrets.KETRYX_PROJECT }}
          api-key: ${{ secrets.KETRYX_API_KEY }}
          commit-sha: ${{ inputs.commit-sha }}
          build-name: "ci-cd"
          test-junit-path: test-results/junit_*.xml
          cyclonedx-json-path: |
            audit-results/sbom.json
          artifact-path: |
            audit-results/sbom.spdx
            audit-results/licenses.csv
            audit-results/licenses.json
            audit-results/licenses_grouped.json
            audit-results/vulnerabilities.json
            test-results/coverage.xml
            test-results/coverage.md
