name: "Scheduled Audit"

on:
  workflow_call:
    secrets:
      AIGNOSTICS_CLIENT_ID_DEVICE:
        required: false
      AIGNOSTICS_REFRESH_TOKEN:
        required: false
      GCP_CREDENTIALS:
        required: false
      BETTERSTACK_AUDIT_HEARTBEAT_URL:
        required: false

jobs:
  audit-scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          version-file: "pyproject.toml"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Install Python, venv and dependencies
        shell: bash
        run: uv sync --all-extras --frozen --link-mode=copy

      - name: Create .env file
        uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f # v2.0.3
        with:
          envkey_AIGNOSTICS_CLIENT_ID_DEVICE: ${{ secrets.AIGNOSTICS_CLIENT_ID_DEVICE }}
          envkey_AIGNOSTICS_REFRESH_TOKEN: ${{ secrets.AIGNOSTICS_REFRESH_TOKEN }}
          fail_on_empty: false

      - name: Set up GCP credentials for bucket access
        shell: bash
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json" >> $GITHUB_ENV

      - name: Audit
        shell: bash
        env:
          BETTERSTACK_AUDIT_HEARTBEAT_URL: "${{ secrets.BETTERSTACK_AUDIT_HEARTBEAT_URL }}"
        run: |
          set +e
          make audit
          EXIT_CODE=$?
          # Provide heartbeat to BetterStack for monitoring/alerting if heartbeat url is configured as secret
          if [ -n "$BETTERSTACK_AUDIT_HEARTBEAT_URL" ]; then
            BETTERSTACK_METADATA_PAYLOAD=$(jq -n \
              --arg github_workflow "${{ github.workflow }}" \
              --arg github_run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              --arg github_run_id "${{ github.run_id }}" \
              --arg github_job "${{ github.job }}" \
              --arg github_sha "${{ github.sha }}" \
              --arg github_actor "${{ github.actor }}" \
              --arg github_repository "${{ github.repository }}" \
              --arg github_ref "${{ github.ref }}" \
              --arg job_status "${{ job.status }}" \
              --arg github_event_name "${{ github.event_name }}" \
              --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              '{
                github: {
                  workflow: $github_workflow,
                  run_url: $github_run_url,
                  run_id: $github_run_id,
                  job: $github_job,
                  sha: $github_sha,
                  actor: $github_actor,
                  repository: $github_repository,
                  ref: $github_ref,
                  event_name: $github_event_name
                },
                job: {
                  status: $job_status,
                },
                timestamp: $timestamp,
              }'
            )

            curl \
              --fail-with-body \
              --silent \
              --request POST \
              --header "Content-Type: application/json" \
              --data-binary "${BETTERSTACK_METADATA_PAYLOAD}" \
              "${BETTERSTACK_AUDIT_HEARTBEAT_URL}/${EXIT_CODE}"
          fi
          exit $EXIT_CODE

      - name: Upload test results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: ${{ always() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        with:
          name: test-results-scheduled
          path: |
            reports/mypy_junit.xml
            reports/sbom.json
            reports/sbom.spdx
            reports/licenses.csv
            reports/licenses.json
            reports/licenses_grouped.json
            reports/vulnerabilities.json
          retention-days: 7
