name: "> Scheduled Test (Hourly)"

on:
  workflow_call:
    inputs:
      platform_environment:
        description: 'Environment to test against, that is staging or production'
        required: false
        default: 'staging'
        type: string
      branch:
        description: 'Branch to checkout (leave empty for default branch)'
        required: false
        default: ''
        type: string
    secrets:
      AIGNOSTICS_CLIENT_ID_DEVICE_STAGING:
        required: true
      AIGNOSTICS_REFRESH_TOKEN_STAGING:
        required: true
      GCP_CREDENTIALS_STAGING:
        required: true
      BETTERSTACK_HEARTBEAT_URL_STAGING:
        required: true
      AIGNOSTICS_CLIENT_ID_DEVICE_PRODUCTION:
        required: true
      AIGNOSTICS_REFRESH_TOKEN_PRODUCTION:
        required: true
      GCP_CREDENTIALS_PRODUCTION:
        required: true
      BETTERSTACK_HEARTBEAT_URL_PRODUCTION:
        required: true
      SENTRY_DSN:
        required: true

env:
  # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
  PYTHONIOENCODING: "utf8"
  AIGNOSTICS_PLATFORM_ENVIRONMENT: ${{ inputs.platform_environment }}

jobs:
  test-scheduled-hourly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version-file: "pyproject.toml"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Install Python, venv and dependencies
        shell: bash
        run: uv sync --all-extras --frozen --link-mode=copy

      - name: Create .env file
        uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f # v2.0.3
        with:
          # The following 3 lines are correct even if vscode complains
          envkey_AIGNOSTICS_API_ROOT: ${{ inputs.platform_environment == 'staging' && 'https://platform-staging.aignostics.com' || 'https://platform.aignostics.com' }}
          envkey_AIGNOSTICS_CLIENT_ID_DEVICE: ${{ inputs.platform_environment == 'staging' && secrets.AIGNOSTICS_CLIENT_ID_DEVICE_STAGING || secrets.AIGNOSTICS_CLIENT_ID_DEVICE_PRODUCTION }}
          envkey_AIGNOSTICS_REFRESH_TOKEN: ${{ inputs.platform_environment == 'staging' && secrets.AIGNOSTICS_REFRESH_TOKEN_STAGING || secrets.AIGNOSTICS_REFRESH_TOKEN_PRODUCTION }}
          envkey_AIGNOSTICS_SENTRY_ENABLED: true
          envkey_AIGNOSTICS_SENTRY_DSN: ${{ secrets.SENTRY_DSN}}
          envkey_AIGNOSTICS_SENTRY_DEBUG: false
          envkey_AIGNOSTICS_SENTRY_SEND_DEFAULT_PII: false
          envkey_AIGNOSTICS_SENTRY_SAMPLE_RATE: 0
          envkey_AIGNOSTICS_SENTRY_TRACES_SAMPLE_RATE: 0
          envkey_AIGNOSTICS_SENTRY_PROFILES_SAMPLE_RATE: 0
          fail_on_empty: false

      - name: Set up GCP credentials for bucket access
        shell: bash
        env:
          GCP_CREDENTIALS: ${{ inputs.platform_environment == 'staging' && secrets.GCP_CREDENTIALS_STAGING || secrets.GCP_CREDENTIALS_PRODUCTION }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json" >> $GITHUB_ENV

      - name: Test / scheduled
        env:
          BETTERSTACK_HEARTBEAT_URL: "${{ inputs.platform_environment == 'staging' && secrets.BETTERSTACK_HEARTBEAT_URL_STAGING || secrets.BETTERSTACK_HEARTBEAT_URL_PRODUCTION }}"
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        shell: bash
        run: |
          set +e
          make test_scheduled
          EXIT_CODE=$?
          # Show test execution in GitHub Job summary
          found_files=0
          for file in reports/pytest_*.md; do
            if [ -f "$file" ]; then
              cat "$file" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              found_files=1
            fi
          done
          if [ $found_files -eq 0 ]; then
            echo "# All scheduled tests passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          # Show test coverage in GitHub Job summary
          if [ -f "reports/coverage.md" ]; then
            cat "reports/coverage.md" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          else
            echo "# No test coverage computed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi

          # Send heartbeat to Sentry, defining the schedule on the fly
          SENTRY_EXIT_CODE=$(sentry-cli monitors run -e CI --schedule "0 * * * *" --check-in-margin 30 --max-runtime 1 scheduled-testing-${{ inputs.platform_environment }}-hourly --timezone "Europe/Berlin" -- sh -c "exit $EXIT_CODE")

          # Provide heartbeat to BetterStack for monitoring/alerting if heartbeat url is configured as secret
          if [ -n "$BETTERSTACK_HEARTBEAT_URL" ]; then
            BETTERSTACK_METADATA_PAYLOAD=$(jq -n \
              --arg github_workflow "${{ github.workflow }}" \
              --arg github_run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              --arg github_run_id "${{ github.run_id }}" \
              --arg github_job "${{ github.job }}" \
              --arg github_sha "${{ github.sha }}" \
              --arg github_actor "${{ github.actor }}" \
              --arg github_repository "${{ github.repository }}" \
              --arg github_ref "${{ github.ref }}" \
              --arg job_status "${{ job.status }}" \
              --arg github_event_name "${{ github.event_name }}" \
              --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              '{
                github: {
                  workflow: $github_workflow,
                  run_url: $github_run_url,
                  run_id: $github_run_id,
                  job: $github_job,
                  sha: $github_sha,
                  actor: $github_actor,
                  repository: $github_repository,
                  ref: $github_ref,
                  event_name: $github_event_name
                },
                job: {
                  status: $job_status,
                },
                timestamp: $timestamp,
              }'
            )
            curl \
              --fail-with-body \
              --silent \
              --request POST \
              --header "Content-Type: application/json" \
              --data-binary "${BETTERSTACK_METADATA_PAYLOAD}" \
              "${BETTERSTACK_HEARTBEAT_URL}/${EXIT_CODE}"
            echo "INFO: Sent heartbeat to betterstack with exit code '${EXIT_CODE}'"
          else
            echo "WARNING: No BetterStack heartbeat URL configured, skipped heartbeat notification."
          fi
          exit $EXIT_CODE

      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ always() && (env.GITHUB_WORKFLOW_RUNTIME != 'ACT') }}
        with:
          name: test-results-scheduled
          path: |
            reports/junit.xml
            reports/coverage.xml
            reports/coverage.md
            reports/coverage_html
            aignostics.log
          retention-days: 7
