name: "Scheduled Testing"

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  test-scheduled:
    uses: ./.github/workflows/_scheduled-test.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      AIGNOSTICS_CLIENT_ID_DEVICE: ${{ secrets.AIGNOSTICS_CLIENT_ID_DEVICE }}
      AIGNOSTICS_REFRESH_TOKEN: ${{ secrets.AIGNOSTICS_REFRESH_TOKEN }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      BETTERSTACK_HEARTBEAT_URL: ${{ secrets.BETTERSTACK_HEARTBEAT_URL }}
